name: cmafinal_app
description: L'application du Comité Monégasque Antidopage.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  http: ^0.12.2
  font_awesome_flutter: ^8.11.0
  animated_size_and_fade: ^1.1.3
  auto_size_text: ^2.1.0
  url_launcher: ^5.7.10
  youtube_player_flutter: ^7.0.0+7
  google_maps_flutter: ^1.0.10
  mailer: ^3.2.1
  intl: 0.15.7
  html: ^0.14.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
    - images/

  fonts:
   - family: Cabin
     fonts:
      - asset: lib/assets/fonts/Cabin-Regular.ttf
      - asset: lib/assets/fonts/Cabin-Italic.ttf
      - asset: lib/assets/fonts/Cabin-Medium.ttf
      - asset : lib/assets/fonts/Cabin-Bold.ttf
        weight : 200
   - family: Lato
     fonts:
        - asset: lib/assets/fonts/Lato-Regular.ttf
        - asset: lib/assets/fonts/Lato-Bold.ttf

